import { useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';
import {
  LayersIcon,
  MapPinIcon,
  SaveIcon,
  SearchIcon,
  Settings2Icon,
  XIcon
} from 'lucide-react';

import { PageHeader } from '../components/ui/PageHeader';
import { Card, CardHeader } from '../components/ui/Card';
import { SearchInput, Select } from '../components/ui/Field';
import { Badge } from '../components/ui/Badge';
import { Button } from '../components/ui/Button';
import { EmptyState } from '../components/ui/Feedback';

import { useAuth } from '../contexts/AuthContext';
import { coreService } from '../services/coreService';
import { ApiError } from '../lib/apiClient';

import { area as fmtArea, number } from '../utils/format';
import { cn } from '../utils/cn';

import type {
  ProyectoResponse,
  LoteResponse,
  PlanoInteractivoDetalleResponse,
  LoteGeometriaResponse
} from '../types/core';

interface StatusFilter {
  code: string;
  label: string;
  dotColor: string;
  badgeStyle: string;
  polygonFill: string;
  polygonStroke: string;
}

interface DisplayGeometria extends LoteGeometriaResponse {
  isAutoGenerated?: boolean;
}

const REAL_STATUSES: StatusFilter[] = [
  {
    code: 'DISPONIBLE',
    label: 'Disponibles',
    dotColor: 'bg-emerald-500',
    badgeStyle: 'bg-emerald-50 border-emerald-300 text-emerald-800 hover:bg-emerald-100',
    polygonFill: '#10b981',
    polygonStroke: '#047857'
  },
  {
    code: 'RESERVADO',
    label: 'Reservados',
    dotColor: 'bg-amber-500',
    badgeStyle: 'bg-amber-50 border-amber-300 text-amber-800 hover:bg-amber-100',
    polygonFill: '#f59e0b',
    polygonStroke: '#b45309'
  },
  {
    code: 'VENDIDO',
    label: 'Vendidos',
    dotColor: 'bg-slate-800',
    badgeStyle: 'bg-slate-100 border-slate-400 text-slate-800 hover:bg-slate-200',
    polygonFill: '#1e293b',
    polygonStroke: '#0f172a'
  },
  {
    code: 'BLOQUEADO',
    label: 'Bloqueados',
    dotColor: 'bg-rose-500',
    badgeStyle: 'bg-rose-50 border-rose-300 text-rose-800 hover:bg-rose-100',
    polygonFill: '#f43f5e',
    polygonStroke: '#be123c'
  },
  {
    code: 'NO_DISPONIBLE',
    label: 'No disponibles',
    dotColor: 'bg-gray-400',
    badgeStyle: 'bg-gray-100 border-gray-300 text-gray-700 hover:bg-gray-200',
    polygonFill: '#9ca3af',
    polygonStroke: '#4b5563'
  }
];

function getPolygonColors(codigoEstadoLote?: string | null) {
  const found = REAL_STATUSES.find((s) => s.code === codigoEstadoLote);
  if (found) {
    return { fill: found.polygonFill, stroke: found.polygonStroke };
  }
  return { fill: '#9ca3af', stroke: '#4b5563' };
}

function naturalCompare(a?: string | null, b?: string | null): number {
  const strA = (a ?? '').trim();
  const strB = (b ?? '').trim();
  return strA.localeCompare(strB, undefined, { numeric: true, sensitivity: 'base' });
}

function buildDisplayGeometries(
  lots: LoteResponse[],
  planDetail: PlanoInteractivoDetalleResponse | null,
  selectedProjectId: number | null
): DisplayGeometria[] {
  if (lots.length === 0) return [];

  const persistedMap = new Map<number, LoteGeometriaResponse>();
  if (planDetail?.lotes) {
    planDetail.lotes.forEach((g) => {
      if (g.activo) {
        persistedMap.set(g.idLote, g);
      }
    });
  }

  const resultGeometries: DisplayGeometria[] = [];
  const unpositionedLots: LoteResponse[] = [];

  lots.forEach((lote) => {
    const persisted = persistedMap.get(lote.idLote);
    if (persisted) {
      resultGeometries.push({
        ...persisted,
        isAutoGenerated: false
      });
    } else {
      unpositionedLots.push(lote);
    }
  });

  if (unpositionedLots.length === 0) {
    return resultGeometries;
  }

  const lotWidth = 68;
  const lotHeight = 55;
  const gapX = 12;
  const rowHeight = 80;
  const stageGap = 35;

  // Si no hay ninguna geometría persistida previa: auto-layout completo de unpositionedLots
  if (resultGeometries.length === 0) {
    type StageGroup = {
      key: string;
      nombre: string;
      manzanas: Map<string, LoteResponse[]>;
    };

    const stagesMap = new Map<string, StageGroup>();

    unpositionedLots.forEach((lote) => {
      const stageKey = String(lote.idEtapa ?? lote.nombreEtapa ?? lote.codigoEtapa ?? 'etapa-default');
      const stageName = lote.nombreEtapa || lote.codigoEtapa || 'Etapa Principal';

      if (!stagesMap.has(stageKey)) {
        stagesMap.set(stageKey, {
          key: stageKey,
          nombre: stageName,
          manzanas: new Map<string, LoteResponse[]>()
        });
      }

      const stageObj = stagesMap.get(stageKey)!;
      const blockKey = lote.nombreManzana || lote.codigoManzana || 'Manzana Unica';

      const blockList = stageObj.manzanas.get(blockKey) ?? [];
      blockList.push(lote);
      stageObj.manzanas.set(blockKey, blockList);
    });

    const sortedStages = Array.from(stagesMap.values()).sort((a, b) =>
      naturalCompare(a.nombre, b.nombre)
    );

    let maxLotsInRow = 1;
    sortedStages.forEach((stg) => {
      stg.manzanas.forEach((mLots) => {
        if (mLots.length > maxLotsInRow) {
          maxLotsInRow = mLots.length;
        }
      });
    });

    const maxRowWidth = maxLotsInRow * lotWidth + (maxLotsInRow - 1) * gapX;
    const usableAreaWidth = Math.max(740, maxRowWidth);

    let currentY = 50;

    sortedStages.forEach((stg) => {
      const sortedBlocks = Array.from(stg.manzanas.entries()).sort(([bKeyA], [bKeyB]) =>
        naturalCompare(bKeyA, bKeyB)
      );

      sortedBlocks.forEach(([_bKey, mLots]) => {
        mLots.sort((lA, lB) => naturalCompare(lA.numero || lA.codigo, lB.numero || lB.codigo));

        const count = mLots.length;
        const rowWidth = count * lotWidth + (count - 1) * gapX;
        const startX = 115 + Math.max(0, Math.floor((usableAreaWidth - rowWidth) / 2));

        mLots.forEach((lote, idx) => {
          const x = startX + idx * (lotWidth + gapX);
          const y = currentY;

          resultGeometries.push({
            idLoteGeometria: -(lote.idLote),
            idProyecto: lote.idProyecto ?? selectedProjectId ?? 0,
            idPlanoInteractivo: planDetail?.plano.idPlanoInteractivo ?? 0,
            idLote: lote.idLote,
            codigoLote: lote.codigo,
            numeroLote: lote.numero,
            puntos: [
              { x, y },
              { x: x + lotWidth, y },
              { x: x + lotWidth, y: y + lotHeight },
              { x, y: y + lotHeight }
            ],
            etiquetaX: Math.round(x + lotWidth / 2),
            etiquetaY: Math.round(y + lotHeight / 2),
            rotacionEtiqueta: 0,
            ordenCapa: 1,
            visible: true,
            interactivo: true,
            activo: true,
            isAutoGenerated: true
          });
        });

        currentY += rowHeight;
      });

      currentY += stageGap;
    });

    return resultGeometries;
  }

  // Caso Híbrido: ya existen algunas geometrías persistidas
  const unpositionedByBlock = new Map<string, LoteResponse[]>();
  unpositionedLots.forEach((lote) => {
    const blockKey = lote.nombreManzana || lote.codigoManzana || 'Manzana Unica';
    const list = unpositionedByBlock.get(blockKey) ?? [];
    list.push(lote);
    unpositionedByBlock.set(blockKey, list);
  });

  const sortedUnpositionedBlocks = Array.from(unpositionedByBlock.entries()).sort(([a], [b]) =>
    naturalCompare(a, b)
  );

  sortedUnpositionedBlocks.forEach(([blockKey, mLots]) => {
    mLots.sort((lA, lB) => naturalCompare(lA.numero || lA.codigo, lB.numero || lB.codigo));

    const existingGeoms = resultGeometries.filter((g) => {
      const l = lots.find((lot) => lot.idLote === g.idLote);
      const bName = l?.nombreManzana || l?.codigoManzana;
      return bName === blockKey;
    });

    if (existingGeoms.length > 0) {
      const avgY =
        existingGeoms.reduce((sum, g) => sum + (g.etiquetaY ?? 0), 0) / existingGeoms.length;
      let maxX = 0;
      existingGeoms.forEach((g) => {
        g.puntos.forEach((p) => {
          if (p.x > maxX) maxX = p.x;
        });
      });

      const y = Math.round(avgY - lotHeight / 2);
      let nextX = maxX + gapX;

      mLots.forEach((lote) => {
        resultGeometries.push({
          idLoteGeometria: -(lote.idLote),
          idProyecto: lote.idProyecto ?? selectedProjectId ?? 0,
          idPlanoInteractivo: planDetail?.plano.idPlanoInteractivo ?? 0,
          idLote: lote.idLote,
          codigoLote: lote.codigo,
          numeroLote: lote.numero,
          puntos: [
            { x: nextX, y },
            { x: nextX + lotWidth, y },
            { x: nextX + lotWidth, y: y + lotHeight },
            { x: nextX, y: y + lotHeight }
          ],
          etiquetaX: Math.round(nextX + lotWidth / 2),
          etiquetaY: Math.round(y + lotHeight / 2),
          rotacionEtiqueta: 0,
          ordenCapa: 1,
          visible: true,
          interactivo: true,
          activo: true,
          isAutoGenerated: true
        });
        nextX += lotWidth + gapX;
      });
    } else {
      let maxY = 50;
      resultGeometries.forEach((g) => {
        g.puntos.forEach((p) => {
          if (p.y + lotHeight > maxY) maxY = p.y + lotHeight;
        });
      });

      const y = maxY + 25;
      let nextX = 115;

      mLots.forEach((lote) => {
        resultGeometries.push({
          idLoteGeometria: -(lote.idLote),
          idProyecto: lote.idProyecto ?? selectedProjectId ?? 0,
          idPlanoInteractivo: planDetail?.plano.idPlanoInteractivo ?? 0,
          idLote: lote.idLote,
          codigoLote: lote.codigo,
          numeroLote: lote.numero,
          puntos: [
            { x: nextX, y },
            { x: nextX + lotWidth, y },
            { x: nextX + lotWidth, y: y + lotHeight },
            { x: nextX, y: y + lotHeight }
          ],
          etiquetaX: Math.round(nextX + lotWidth / 2),
          etiquetaY: Math.round(y + lotHeight / 2),
          rotacionEtiqueta: 0,
          ordenCapa: 1,
          visible: true,
          interactivo: true,
          activo: true,
          isAutoGenerated: true
        });
        nextX += lotWidth + gapX;
      });
    }
  });

  return resultGeometries;
}

export function LotMap() {
  const { can } = useAuth();
  const canConfigurePlan = can('lots.configure');
  const [isEditingPlan, setIsEditingPlan] = useState(false);
  const [draftGeometries, setDraftGeometries] = useState<DisplayGeometria[]>([]);
  const [savingPlan, setSavingPlan] = useState(false);

  const [projects, setProjects] = useState<ProyectoResponse[]>([]);
  const [selectedProjectId, setSelectedProjectId] = useState<number | null>(null);
  const [lots, setLots] = useState<LoteResponse[]>([]);
  const [planDetail, setPlanDetail] = useState<PlanoInteractivoDetalleResponse | null>(null);
  const [loadingProjects, setLoadingProjects] = useState(true);
  const [loadingPlan, setLoadingPlan] = useState(false);
  const [selectedLotId, setSelectedLotId] = useState<number | null>(null);

  const [query, setQuery] = useState('');
  const [activeStatuses, setActiveStatuses] = useState<string[]>(
    REAL_STATUSES.map((s) => s.code)
  );

  // Cargar proyectos activos al montar
  useEffect(() => {
    let isMounted = true;
    setLoadingProjects(true);
    coreService
      .getActiveProjects()
      .then((res) => {
        if (!isMounted) return;
        setProjects(res);
        if (res.length > 0) {
          setSelectedProjectId(res[0].idProyecto);
        }
      })
      .catch((err: unknown) => {
        if (!isMounted) return;
        const msg = err instanceof ApiError ? err.message : 'Error al cargar proyectos activos';
        toast.error(msg);
      })
      .finally(() => {
        if (isMounted) setLoadingProjects(false);
      });

    return () => {
      isMounted = false;
    };
  }, []);

  // Al cambiar de proyecto, cargar lotes y plano en paralelo
  useEffect(() => {
    if (!selectedProjectId) {
      setLots([]);
      setPlanDetail(null);
      return;
    }

    let isMounted = true;
    setLoadingPlan(true);
    setSelectedLotId(null);

    Promise.allSettled([
      coreService.searchLots({ idProyecto: selectedProjectId, activo: true }),
      coreService.getCurrentPlanDetail(selectedProjectId)
    ]).then(([lotsResult, planResult]) => {
      if (!isMounted) return;

      if (lotsResult.status === 'fulfilled') {
        setLots(lotsResult.value);
      } else {
        setLots([]);
        const err = lotsResult.reason;
        const msg = err instanceof ApiError ? err.message : 'Error al cargar lotes del proyecto';
        toast.error(msg);
      }

      if (planResult.status === 'fulfilled') {
        setPlanDetail(planResult.value);
      } else {
        setPlanDetail(null);
      }

      setLoadingPlan(false);
    });

    return () => {
      isMounted = false;
    };
  }, [selectedProjectId]);

  const currentProject = useMemo(() => {
    return projects.find((p) => p.idProyecto === selectedProjectId) ?? null;
  }, [projects, selectedProjectId]);

  const displayGeometries = useMemo(() => {
    return buildDisplayGeometries(lots, planDetail, selectedProjectId);
  }, [lots, planDetail, selectedProjectId]);

  useEffect(() => {
    if (!isEditingPlan) {
      setDraftGeometries([]);
      return;
    }

    setDraftGeometries(
      displayGeometries.map((geom) => ({
        ...geom,
        puntos: geom.puntos.map((p) => ({ ...p }))
      }))
    );
  }, [isEditingPlan, displayGeometries]);

  const renderedGeometries = isEditingPlan
    ? draftGeometries
    : displayGeometries;

  const handleCancelPlanEditing = () => {
    setDraftGeometries([]);
    setIsEditingPlan(false);
  };

  const handleSavePlan = async () => {
    if (!planDetail?.plano) {
      toast.error(
        'Este proyecto todavía no tiene un plano vigente para guardar la configuración.'
      );
      return;
    }

    const changedGeometries = draftGeometries.filter((draft) => {
      const original = displayGeometries.find(
        (geom) => geom.idLote === draft.idLote
      );

      if (!original) return true;

      return (
        JSON.stringify(draft.puntos) !== JSON.stringify(original.puntos) ||
        draft.etiquetaX !== original.etiquetaX ||
        draft.etiquetaY !== original.etiquetaY ||
        draft.rotacionEtiqueta !== original.rotacionEtiqueta
      );
    });

    if (changedGeometries.length === 0) {
      toast.info('No hay cambios en la distribución del plano.');
      return;
    }

    setSavingPlan(true);

    try {
      await Promise.all(
        changedGeometries.map((geom) =>
          coreService.saveLotGeometry({
            idPlanoInteractivo: planDetail.plano.idPlanoInteractivo,
            idLote: geom.idLote,
            puntos: geom.puntos,
            etiquetaX: geom.etiquetaX ?? null,
            etiquetaY: geom.etiquetaY ?? null,
            rotacionEtiqueta: geom.rotacionEtiqueta ?? 0,
            ordenCapa: geom.ordenCapa ?? 1,
            visible: geom.visible,
            interactivo: geom.interactivo,
            observaciones: geom.observaciones ?? null
          })
        )
      );

      if (selectedProjectId) {
        const refreshedPlan =
          await coreService.getCurrentPlanDetail(selectedProjectId);

        setPlanDetail(refreshedPlan);
      }

      setIsEditingPlan(false);
      setDraftGeometries([]);

      toast.success(
        `${changedGeometries.length} lote(s) actualizados correctamente.`
      );
    } catch (err: unknown) {
      const message =
        err instanceof ApiError
          ? err.message
          : 'No se pudo guardar la configuración del plano.';

      toast.error(message);
    } finally {
      setSavingPlan(false);
    }
  };

  const { persistedCount, autoCount } = useMemo(() => {
    let p = 0;
    let a = 0;
    displayGeometries.forEach((g) => {
      if (g.isAutoGenerated) {
        a++;
      } else {
        p++;
      }
    });
    return { persistedCount: p, autoCount: a };
  }, [displayGeometries]);

  const canvasDimensions = useMemo(() => {
    let maxX = 920;
    let maxY = 720;

    renderedGeometries.forEach((g) => {
      g.puntos.forEach((p) => {
        if (p.x + 40 > maxX) maxX = Math.ceil(p.x + 40);
        if (p.y + 40 > maxY) maxY = Math.ceil(p.y + 40);
      });
      if (g.etiquetaX != null && g.etiquetaX + 40 > maxX) maxX = Math.ceil(g.etiquetaX + 40);
      if (g.etiquetaY != null && g.etiquetaY + 40 > maxY) maxY = Math.ceil(g.etiquetaY + 40);
    });

    if (planDetail?.plano) {
      if (planDetail.plano.anchoReferencia > maxX) maxX = planDetail.plano.anchoReferencia;
      if (planDetail.plano.altoReferencia > maxY) maxY = planDetail.plano.altoReferencia;
    }

    return {
      width: Math.max(920, maxX),
      height: Math.max(720, maxY)
    };
  }, [renderedGeometries, planDetail]);

  const manzanaLabels = useMemo(() => {
    const rows = new Map<string, number[]>();

    renderedGeometries.forEach((geom) => {
      const lote = lots.find((l) => l.idLote === geom.idLote);
      const manzanaCode = lote?.nombreManzana || lote?.codigoManzana;

      if (!manzanaCode || geom.etiquetaY == null) {
        return;
      }

      const values = rows.get(manzanaCode) ?? [];
      values.push(Number(geom.etiquetaY));
      rows.set(manzanaCode, values);
    });

    return Array.from(rows.entries())
      .map(([codigo, ys]) => ({
        codigo,
        y: ys.reduce((sum, value) => sum + value, 0) / ys.length
      }))
      .sort((a, b) => a.y - b.y);
  }, [renderedGeometries, lots]);

  const planSubtitleText = useMemo(() => {
    if (planDetail?.plano) {
      const v = planDetail.plano.numeroVersion;
      if (autoCount === 0) {
        return `Plano V${v} · ${persistedCount} de ${lots.length} lotes posicionados`;
      }
      return `Plano V${v} · ${persistedCount} configurados · ${autoCount} automáticos`;
    }
    return `Distribución automática · ${lots.length} lotes`;
  }, [planDetail, persistedCount, autoCount, lots.length]);

  const counts = useMemo(() => {
    const acc: Record<string, number> = {
      Total: lots.length,
      DISPONIBLE: 0,
      RESERVADO: 0,
      VENDIDO: 0,
      BLOQUEADO: 0,
      NO_DISPONIBLE: 0
    };

    lots.forEach((l) => {
      const st = l.codigoEstadoLote || 'NO_DISPONIBLE';
      if (acc[st] !== undefined) {
        acc[st]++;
      } else {
        acc.NO_DISPONIBLE++;
      }
    });

    return acc;
  }, [lots]);

  const toggleStatus = (code: string) => {
    setActiveStatuses((prev) =>
      prev.includes(code) ? prev.filter((s) => s !== code) : [...prev, code]
    );
  };

  const filteredLotIds = useMemo(() => {
    const q = query.trim().toLowerCase();
    const matches = lots.filter((l) => {
      const matchQuery =
        !q ||
        l.codigo.toLowerCase().includes(q) ||
        (l.numero && l.numero.toLowerCase().includes(q)) ||
        (l.nombreManzana && l.nombreManzana.toLowerCase().includes(q)) ||
        (l.codigoManzana && l.codigoManzana.toLowerCase().includes(q)) ||
        (l.nombreEtapa && l.nombreEtapa.toLowerCase().includes(q));

      const st = l.codigoEstadoLote || 'NO_DISPONIBLE';
      const matchStatus = activeStatuses.includes(st);

      return matchQuery && matchStatus;
    });
    return new Set(matches.map((l) => l.idLote));
  }, [lots, query, activeStatuses]);

  const selectedLot = useMemo(() => {
    if (selectedLotId === null) return null;
    return lots.find((l) => l.idLote === selectedLotId) ?? null;
  }, [lots, selectedLotId]);

  if (loadingProjects) {
    return (
      <div className="flex h-64 items-center justify-center">
        <p className="text-brand-500 text-sm">Cargando proyectos...</p>
      </div>
    );
  }

  if (projects.length === 0) {
    return (
      <div>
        <PageHeader
          title="Plano interactivo"
          description="Consulta la disponibilidad del inventario por etapa y manzana. Selecciona un lote para ver su información comercial."
          meta={
            currentProject ? (
              <>
                <Badge tone="brand">{currentProject.nombre}</Badge>
                <span className="text-[12px] text-brand-400">
                  {number(lots.length)} lotes ·{' '}
                  {currentProject.distrito ||
                    currentProject.provincia ||
                    'Ubicación n/d'}
                </span>
              </>
            ) : undefined
          }
          actions={
            canConfigurePlan ? (
              isEditingPlan ? (
                <div className="flex items-center gap-2">
                  <Button
                    icon={XIcon}
                    onClick={handleCancelPlanEditing}
                    disabled={savingPlan}
                    className="border-brand-200 text-brand-700 hover:bg-brand-50"
                  >
                    Cancelar
                  </Button>

                  <Button
                    icon={SaveIcon}
                    onClick={handleSavePlan}
                    disabled={savingPlan}
                    className="bg-brand-900 text-white hover:bg-brand-800"
                  >
                    {savingPlan ? 'Guardando...' : 'Guardar cambios'}
                  </Button>
                </div>
              ) : (
                <Button
                  icon={Settings2Icon}
                  onClick={() => setIsEditingPlan(true)}
                  className="border-brand-200 text-brand-800 hover:bg-brand-50"
                >
                  Configurar plano
                </Button>
              )
            ) : undefined
          }
        />
      </div>
    );
  }

  return (
    <div>
      <PageHeader
        title="Plano interactivo"
        description="Consulta la disponibilidad del inventario por etapa y manzana. Selecciona un lote para ver su información comercial."
        meta={
          currentProject ? (
            <>
              <Badge tone="brand">{currentProject.nombre}</Badge>
              <span className="text-[12px] text-brand-400">
                {number(lots.length)} lotes · {currentProject.distrito || currentProject.provincia || 'Ubicación n/d'}
              </span>
            </>
          ) : undefined
        }
        actions={
          canConfigurePlan ? (
            isEditingPlan ? (
              <div className="flex items-center gap-2">
                <Button
                  icon={XIcon}
                  onClick={handleCancelPlanEditing}
                  disabled={savingPlan}
                  className="border-brand-200 text-brand-700 hover:bg-brand-50"
                >
                  Cancelar
                </Button>

                <Button
                  icon={SaveIcon}
                  onClick={handleSavePlan}
                  disabled={savingPlan}
                  className="bg-brand-900 text-white hover:bg-brand-800"
                >
                  {savingPlan ? 'Guardando...' : 'Guardar cambios'}
                </Button>
              </div>
            ) : (
              <Button
                icon={Settings2Icon}
                onClick={() => setIsEditingPlan(true)}
                className="border-brand-200 text-brand-800 hover:bg-brand-50"
              >
                Configurar plano
              </Button>
            )
          ) : undefined
        }
      />

      <div className="grid grid-cols-1 gap-4 xl:grid-cols-[minmax(0,1fr)_340px]">
        <Card>
          <div className="flex flex-wrap items-center gap-3 border-b border-brand-100 px-5 py-3.5">
            <Select
              value={selectedProjectId ?? ''}
              onChange={(e) => setSelectedProjectId(Number(e.target.value))}
              aria-label="Proyecto"
              className="w-[220px]"
            >
              {projects.map((p) => (
                <option key={p.idProyecto} value={p.idProyecto}>
                  {p.nombre}
                </option>
              ))}
            </Select>

            <SearchInput
              value={query}
              onValueChange={setQuery}
              placeholder="Buscar por lote, manzana o etapa..."
              label="Buscar lote"
              className="w-full sm:w-64"
            />

            <div className="ml-auto flex flex-wrap items-center gap-1.5">
              {REAL_STATUSES.map((st) => {
                const on = activeStatuses.includes(st.code);
                const count = counts[st.code] ?? 0;

                return (
                  <button
                    key={st.code}
                    type="button"
                    onClick={() => toggleStatus(st.code)}
                    aria-pressed={on}
                    className={cn(
                      'inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[12px] font-medium transition-colors duration-150 ease-smooth',
                      on
                        ? st.badgeStyle
                        : 'border-brand-200 bg-white text-brand-300 hover:text-brand-500'
                    )}
                  >
                    <span className={cn('h-1.5 w-1.5 rounded-full', st.dotColor)} />
                    {st.label}
                    <span className="tabular">{count}</span>
                  </button>
                );
              })}
            </div>
          </div>

          <div className="p-5">
            {loadingPlan ? (
              <div className="flex h-80 items-center justify-center">
                <p className="text-brand-400 text-sm">Cargando plano interactivo...</p>
              </div>
            ) : lots.length === 0 ? (
              <EmptyState
                title="Proyecto sin lotes"
                description="Este proyecto todavía no tiene lotes registrados."
                icon={MapPinIcon}
              />
            ) : (
              <div className="space-y-3">
                <div className="flex items-center justify-between border-b border-brand-100 pb-3 text-[13px]">
                  <div className="flex items-center gap-2 font-medium text-brand-700">
                    <LayersIcon className="h-4 w-4 text-brand-400" />
                    <span>
                      {planDetail?.plano
                        ? `Plano V${planDetail.plano.numeroVersion}`
                        : 'Distribución automática'}
                    </span>
                  </div>
                  <span className="text-brand-500 font-medium">{planSubtitleText}</span>
                </div>

                <div className="overflow-auto rounded-xl border border-brand-200 bg-white p-4 shadow-sm">
                  <svg
                    viewBox={`0 0 ${canvasDimensions.width} ${canvasDimensions.height}`}
                    preserveAspectRatio="xMidYMid meet"
                    className="w-full h-auto min-h-[620px] max-h-[720px] select-none"
                  >
                    <defs>
                      <filter
                        id="lot-shadow"
                        x="-20%"
                        y="-20%"
                        width="140%"
                        height="140%"
                      >
                        <feDropShadow
                          dx="0"
                          dy="2"
                          stdDeviation="2"
                          floodColor="#0f172a"
                          floodOpacity="0.12"
                        />
                      </filter>
                    </defs>

                    {/* Fondo suave */}
                    <rect
                      x="0"
                      y="0"
                      width={canvasDimensions.width}
                      height={canvasDimensions.height}
                      rx="18"
                      fill="#f8fafc"
                    />

                    {/* Línea horizontal de separación entre bloques de manzanas si aplica */}
                    <line
                      x1="100"
                      y1="275"
                      x2={canvasDimensions.width - 20}
                      y2="275"
                      stroke="#e2e8f0"
                      strokeWidth="1"
                      strokeDasharray="6 6"
                    />

                    {/* Leyendas de manzanas a la izquierda */}
                    {manzanaLabels.map((row) => (
                      <g key={row.codigo}>
                        <rect
                          x="22"
                          y={row.y - 19}
                          width="64"
                          height="38"
                          rx="11"
                          fill="#ffffff"
                          stroke="#cbd5e1"
                          strokeWidth="1.5"
                        />

                        <text
                          x="54"
                          y={row.y}
                          textAnchor="middle"
                          dominantBaseline="central"
                          fontSize="13"
                          fontWeight="700"
                          fill="#334155"
                          pointerEvents="none"
                        >
                          {row.codigo}
                        </text>
                      </g>
                    ))}

                    {/* Lotes */}
                    {renderedGeometries.map((geom: DisplayGeometria) => {
                      const lote = lots.find((l) => l.idLote === geom.idLote);
                      const isMatch = filteredLotIds.has(geom.idLote);
                      const isSelected = selectedLotId === geom.idLote;
                      const colors = getPolygonColors(lote?.codigoEstadoLote);

                      const pointsStr = geom.puntos.map((p) => `${p.x},${p.y}`).join(' ');

                      return (
                        <g key={geom.idLoteGeometria} className="cursor-pointer">
                          <polygon
                            points={pointsStr}
                            fill={colors.fill}
                            stroke={isSelected ? '#2563eb' : colors.stroke}
                            strokeWidth={isSelected ? 3 : 1.75}
                            strokeLinejoin="round"
                            filter="url(#lot-shadow)"
                            opacity={isMatch ? (isSelected ? 1 : 0.9) : 0.18}
                            className="transition-all duration-150 hover:brightness-105"
                            onClick={() => setSelectedLotId(geom.idLote)}
                          >
                            <title>
                              {geom.codigoLote} - {lote?.nombreEstadoLote || lote?.codigoEstadoLote || 'Sin estado'}
                            </title>
                          </polygon>

                          {geom.etiquetaX != null && geom.etiquetaY != null && (
                            <text
                              x={geom.etiquetaX}
                              y={geom.etiquetaY}
                              transform={
                                geom.rotacionEtiqueta
                                  ? `rotate(${geom.rotacionEtiqueta}, ${geom.etiquetaX}, ${geom.etiquetaY})`
                                  : undefined
                              }
                              textAnchor="middle"
                              dominantBaseline="central"
                              fontSize="12"
                              fontWeight="700"
                              fill="#ffffff"
                              pointerEvents="none"
                              opacity={isMatch ? 1 : 0.3}
                            >
                              {geom.codigoLote}
                            </text>
                          )}
                        </g>
                      );
                    })}
                  </svg>
                </div>
              </div>
            )}
          </div>
        </Card>

        {/* Panel lateral de lote seleccionado */}
        <Card className="h-fit xl:sticky xl:top-6">
          <CardHeader
            title={selectedLot ? `Lote ${selectedLot.codigo}` : 'Detalle del lote'}
            description={
              selectedLot
                ? `${selectedLot.nombreManzana || selectedLot.codigoManzana || ''} · ${selectedLot.nombreEtapa || selectedLot.codigoEtapa || ''}`
                : undefined
            }
          />

          {!selectedLot ? (
            <EmptyState
              title="Selecciona un lote"
              description="Haz clic en cualquier polígono del plano para ver la ficha del lote."
              icon={SearchIcon}
            />
          ) : (
            <dl className="divide-y divide-brand-50">
              <div className="flex items-baseline justify-between gap-3 px-5 py-2.5">
                <dt className="text-[12px] text-brand-400">Código</dt>
                <dd className="text-right text-[13px] font-medium text-brand-800">
                  {selectedLot.codigo}
                </dd>
              </div>

              <div className="flex items-baseline justify-between gap-3 px-5 py-2.5">
                <dt className="text-[12px] text-brand-400">Número</dt>
                <dd className="text-right text-[13px] font-medium text-brand-800">
                  {selectedLot.numero || '-'}
                </dd>
              </div>

              <div className="flex items-baseline justify-between gap-3 px-5 py-2.5">
                <dt className="text-[12px] text-brand-400">Etapa</dt>
                <dd className="text-right text-[13px] font-medium text-brand-800">
                  {selectedLot.nombreEtapa || selectedLot.codigoEtapa || '-'}
                </dd>
              </div>

              <div className="flex items-baseline justify-between gap-3 px-5 py-2.5">
                <dt className="text-[12px] text-brand-400">Manzana</dt>
                <dd className="text-right text-[13px] font-medium text-brand-800">
                  {selectedLot.nombreManzana || selectedLot.codigoManzana || '-'}
                </dd>
              </div>

              <div className="flex items-baseline justify-between gap-3 px-5 py-2.5">
                <dt className="text-[12px] text-brand-400">Zona</dt>
                <dd className="text-right text-[13px] font-medium text-brand-800">
                  {selectedLot.nombreZona || selectedLot.codigoZona || '-'}
                </dd>
              </div>

              <div className="flex items-baseline justify-between gap-3 px-5 py-2.5">
                <dt className="text-[12px] text-brand-400">Tipo</dt>
                <dd className="text-right text-[13px] font-medium text-brand-800">
                  {selectedLot.nombreTipoLote || selectedLot.codigoTipoLote || '-'}
                </dd>
              </div>

              <div className="flex items-baseline justify-between gap-3 px-5 py-2.5">
                <dt className="text-[12px] text-brand-400">Área</dt>
                <dd className="text-right text-[13px] font-medium text-brand-800">
                  {selectedLot.areaM2 != null ? fmtArea(selectedLot.areaM2) : '-'}
                </dd>
              </div>

              <div className="flex items-baseline justify-between gap-3 px-5 py-2.5">
                <dt className="text-[12px] text-brand-400">Estado</dt>
                <dd className="text-right text-[13px] font-medium text-brand-800">
                  {selectedLot.nombreEstadoLote || selectedLot.codigoEstadoLote || '-'}
                </dd>
              </div>

              <div className="flex items-baseline justify-between gap-3 px-5 py-2.5">
                <dt className="text-[12px] text-brand-400">Activo</dt>
                <dd className="text-right text-[13px] font-medium text-brand-800">
                  {selectedLot.activo ? 'Sí' : 'No'}
                </dd>
              </div>
            </dl>
          )}
        </Card>
      </div>
    </div>
  );
}