-- =============================================================================
-- LIMPIEZA CONTROLADA DEL MODELO MONOLITHE EN SUPABASE
-- =============================================================================
-- Elimina solo tablas conocidas del esquema anterior y del esquema definitivo.
-- No elimina el schema public ni objetos internos de Supabase.
-- ATENCION: este script elimina los datos contenidos en estas tablas.
-- =============================================================================

SET search_path TO public;

DROP TABLE IF EXISTS public.asignacion_interes CASCADE;
DROP TABLE IF EXISTS public.detalle_venta CASCADE;
DROP TABLE IF EXISTS public.detalle_reserva CASCADE;
DROP TABLE IF EXISTS public.estado CASCADE;
DROP TABLE IF EXISTS public.evento_auditoria CASCADE;
DROP TABLE IF EXISTS public.saldo_inicial CASCADE;
DROP TABLE IF EXISTS public.transferencia CASCADE;
DROP TABLE IF EXISTS public.movimiento CASCADE;
DROP TABLE IF EXISTS public.cuenta_financiera CASCADE;
DROP TABLE IF EXISTS public.categoria_financiera CASCADE;
DROP TABLE IF EXISTS public.preferencia CASCADE;
DROP TABLE IF EXISTS public.plantilla CASCADE;
DROP TABLE IF EXISTS public.envio_notificacion CASCADE;
DROP TABLE IF EXISTS public.notificacion CASCADE;
DROP TABLE IF EXISTS public.consulta_web CASCADE;
DROP TABLE IF EXISTS public.ficha_proyecto CASCADE;
DROP TABLE IF EXISTS public.vinculo_multimedia CASCADE;
DROP TABLE IF EXISTS public.multimedia CASCADE;
DROP TABLE IF EXISTS public.elemento_seccion CASCADE;
DROP TABLE IF EXISTS public.seccion CASCADE;
DROP TABLE IF EXISTS public.pagina CASCADE;
DROP TABLE IF EXISTS public.comision CASCADE;
DROP TABLE IF EXISTS public.regla_comision CASCADE;
DROP TABLE IF EXISTS public.asignacion_venta CASCADE;
DROP TABLE IF EXISTS public.asignacion_prospecto CASCADE;
DROP TABLE IF EXISTS public.asesor CASCADE;
DROP TABLE IF EXISTS public.historial_plan CASCADE;
DROP TABLE IF EXISTS public.voucher CASCADE;
DROP TABLE IF EXISTS public.aplicacion_pago CASCADE;
DROP TABLE IF EXISTS public.pago CASCADE;
DROP TABLE IF EXISTS public.cuota CASCADE;
DROP TABLE IF EXISTS public.plan_pago CASCADE;
DROP TABLE IF EXISTS public.documento_contractual CASCADE;
DROP TABLE IF EXISTS public.contrato CASCADE;
DROP TABLE IF EXISTS public.participacion_venta CASCADE;
DROP TABLE IF EXISTS public.venta CASCADE;
DROP TABLE IF EXISTS public.reserva CASCADE;
DROP TABLE IF EXISTS public.consentimiento CASCADE;
DROP TABLE IF EXISTS public.cliente CASCADE;
DROP TABLE IF EXISTS public.seguimiento CASCADE;
DROP TABLE IF EXISTS public.interes_comercial CASCADE;
DROP TABLE IF EXISTS public.prospecto CASCADE;
DROP TABLE IF EXISTS public.geometria_lote CASCADE;
DROP TABLE IF EXISTS public.plano_interactivo CASCADE;
DROP TABLE IF EXISTS public.historial_lote CASCADE;
DROP TABLE IF EXISTS public.precio_lote CASCADE;
DROP TABLE IF EXISTS public.lote CASCADE;
DROP TABLE IF EXISTS public.ajuste_precio CASCADE;
DROP TABLE IF EXISTS public.tarifa CASCADE;
DROP TABLE IF EXISTS public.etapa_comercial CASCADE;
DROP TABLE IF EXISTS public.zona CASCADE;
DROP TABLE IF EXISTS public.manzana CASCADE;
DROP TABLE IF EXISTS public.etapa CASCADE;
DROP TABLE IF EXISTS public.proyecto CASCADE;
DROP TABLE IF EXISTS public.sesion CASCADE;
DROP TABLE IF EXISTS public.token_recuperacion CASCADE;
DROP TABLE IF EXISTS public.asignacion_permiso CASCADE;
DROP TABLE IF EXISTS public.asignacion_rol CASCADE;
DROP TABLE IF EXISTS public.permiso CASCADE;
DROP TABLE IF EXISTS public.rol CASCADE;
DROP TABLE IF EXISTS public.usuario CASCADE;
DROP TABLE IF EXISTS public.direccion CASCADE;
DROP TABLE IF EXISTS public.contacto CASCADE;
DROP TABLE IF EXISTS public.documento_identidad CASCADE;
DROP TABLE IF EXISTS public.persona CASCADE;
DROP TABLE IF EXISTS public.tipo_cuenta CASCADE;
DROP TABLE IF EXISTS public.estado_movimiento CASCADE;
DROP TABLE IF EXISTS public.tipo_movimiento CASCADE;
DROP TABLE IF EXISTS public.estado_envio CASCADE;
DROP TABLE IF EXISTS public.canal_notificacion CASCADE;
DROP TABLE IF EXISTS public.tipo_notificacion CASCADE;
DROP TABLE IF EXISTS public.estado_consulta_web CASCADE;
DROP TABLE IF EXISTS public.uso_multimedia CASCADE;
DROP TABLE IF EXISTS public.tipo_multimedia CASCADE;
DROP TABLE IF EXISTS public.tipo_seccion CASCADE;
DROP TABLE IF EXISTS public.estado_publicacion CASCADE;
DROP TABLE IF EXISTS public.estado_comision CASCADE;
DROP TABLE IF EXISTS public.tipo_calculo_comision CASCADE;
DROP TABLE IF EXISTS public.estado_asesor CASCADE;
DROP TABLE IF EXISTS public.tipo_asesor CASCADE;
DROP TABLE IF EXISTS public.tipo_aplicacion_pago CASCADE;
DROP TABLE IF EXISTS public.estado_pago CASCADE;
DROP TABLE IF EXISTS public.estado_voucher CASCADE;
DROP TABLE IF EXISTS public.metodo_pago CASCADE;
DROP TABLE IF EXISTS public.estado_cuota CASCADE;
DROP TABLE IF EXISTS public.estado_plan_pago CASCADE;
DROP TABLE IF EXISTS public.modalidad_venta CASCADE;
DROP TABLE IF EXISTS public.estado_usuario CASCADE;
DROP TABLE IF EXISTS public.estado_contrato CASCADE;
DROP TABLE IF EXISTS public.tipo_contrato CASCADE;
DROP TABLE IF EXISTS public.estado_venta CASCADE;
DROP TABLE IF EXISTS public.estado_reserva CASCADE;
DROP TABLE IF EXISTS public.tipo_consentimiento CASCADE;
DROP TABLE IF EXISTS public.tipo_seguimiento CASCADE;
DROP TABLE IF EXISTS public.origen_prospecto CASCADE;
DROP TABLE IF EXISTS public.estado_prospecto CASCADE;
DROP TABLE IF EXISTS public.tipo_contacto CASCADE;
DROP TABLE IF EXISTS public.tipo_ajuste_precio CASCADE;
DROP TABLE IF EXISTS public.tipo_tarifa CASCADE;
DROP TABLE IF EXISTS public.tipo_documento CASCADE;
DROP TABLE IF EXISTS public.moneda CASCADE;
DROP TABLE IF EXISTS public.tipo_lote CASCADE;
DROP TABLE IF EXISTS public.estado_lote CASCADE;
DROP TABLE IF EXISTS public.estado_manzana CASCADE;
DROP TABLE IF EXISTS public.estado_etapa CASCADE;
DROP TABLE IF EXISTS public.estado_proyecto CASCADE;

DROP FUNCTION IF EXISTS public.set_fecha_actualizacion() CASCADE;
